name: C bindings (manual)

permissions: read-all

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test:
    name: build (Windows)
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: install openssl
        uses: ./.github/actions/win_install_openssl
        with:
          architecture: x64
          linking: static

      - name: setup msbuild
        uses: microsoft/setup-msbuild@v3

      - name: install boost
        shell: cmd
        run: |
          git clone --depth=1 --recurse-submodules -j10 --branch=boost-1.78.0 https://github.com/boostorg/boost.git
          cd boost
          bootstrap.bat

      - name: boost headers
        shell: cmd
        run: |
          cd boost
          .\b2 headers

      - name: build
        shell: cmd
        run: |
          set BOOST_ROOT=%CD%\boost
          set BOOST_BUILD_PATH=%BOOST_ROOT%\tools\build
          set PATH=%BOOST_ROOT%;%PATH%

          cd bindings\c
          b2 address-model=64 release openssl-include="C:\Program Files\OpenSSL\include" openssl-lib="C:\Program Files\OpenSSL\lib"
