name: Python bindings (manual)

permissions: read-all

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test:
    name: build (Windows)
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1
          filter: tree:0

      - uses: actions/setup-python@v7
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: install tox and setuptools
        run: |
          python -m pip install --upgrade pip setuptools tox

      - name: install openssl:x64-windows-static
        uses: ./.github/actions/win_install_openssl
        with:
          architecture: x64
          linking: static

      - name: setup msbuild
        uses: microsoft/setup-msbuild@v3

      - name: install boost
        shell: cmd
        run: |
          git clone --depth=1 --recurse-submodules -j10 --branch=boost-1.91.0 https://github.com/boostorg/boost.git
          cd boost
          bootstrap.bat

      - name: boost headers
        shell: cmd
        run: |
          cd boost
          .\b2 headers

      - name: build/test with tox
        shell: cmd
        run: |
          set BOOST_ROOT=%CD%\boost
          set PATH=%BOOST_ROOT%;%PATH%
          set PYTHON_INTERPRETER=python
          set B2_EXTRA_ARGS=openssl-include="C:\Program Files\OpenSSL\include" openssl-lib="C:\Program Files\OpenSSL\lib"
          tox -e py
